// Mocks generated by Mockito 5.0.2 from annotations
// in assist_agro/test/features/admin/data/datasources/login_datasource_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:assist_agro/core/adapters/web_adapter.dart' as _i3;
import 'package:assist_agro/core/core/core_handler.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeCoreHandle<Type> extends _i1.Fake implements _i2.CoreHandle<Type> {}

/// A class which mocks [WebAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebAdapter extends _i1.Mock implements _i3.WebAdapter {
  MockWebAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CoreHandle<Map<String, dynamic>>> get(
          {String? url, Map<String, Map<String, dynamic>>? queryParams}) =>
      (super.noSuchMethod(
          Invocation.method(#get, [], {#url: url, #queryParams: queryParams}),
          returnValue:
              Future.value(_FakeCoreHandle<Map<String, dynamic>>())) as _i4
          .Future<_i2.CoreHandle<Map<String, dynamic>>>);
}
